### ISSUE TITLE
perl users jp をgithub pages に移管する実験

### ISSUE THREAD

**Issue by kfly8** [kfly8/test-perl-users-jp#1]
# TODO
- [x] 記事をdocs配下に吐き出す
- [ ] 整える
  - [ ] title, description, tags をいい感じにする
  - [ ] 日付をいい感じにする
  - [ ] ビルド時のメッセージ
  - [ ] layout, css を整える
  -  [ ] code prettify
  - [ ] footnotes
  - [ ] 記事一覧ページの生成
  - [ ] RSS Feed
- [ ] 追加
    - [ ] twitter card を整える
- [ ] 運用
  - [ ] merge repo? perl-users.jp にリポジトリの作らせてもらう？
  - [x] GitHub Actions でいい感じにビルド
  - [ ] Google Analytics
- [ ] README の整理

**Comment by kfly8** [comment]
GitHub Actions を使って、自動でデプロイするのは、これらを使ってできた。便利。

https://github.com/peaceiris/actions-gh-pages
https://github.com/marketplace/actions/setup-perl-environment

**Comment by kfly8** [comment]
リポジトリを移動して実施。

https://github.com/perl-users-jp/test-perl-users-jp/projects/1
